### PR TITLE
Add find_by_onestop_ids, find_by_onestop_ids! methods

### LINKED ISSUE #330: SSP API: Raise error if missing Stop/Operator/Route
Raise error if stop/operator/route onestop_id not found.

### PR DESCRIPTION
**Pull request by irees**
Allow easier detection of missing records when multiple are specified,
e.g. SSP API.

Resolves #330

### CODE REVIEW

**Comment by irees** [comment]
@drewda This PR implements a multiple find_by_onestop_ids method, and allows us to raise an exception in the SSP controller if an invalid/missing onestop ID is specified. (Fixes issue found with Greg)

**Comment by drewda** [comment]
@irees a recommendation: rewrite `HasAOnestopId.find_by_onestop_ids!` to just use `self.find([])`: http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find That should raise an exception when one of the IDs isn't found.

**Comment by irees** [comment]
@drewda I updated it to use .pluck(:onestop_id) to check for missing IDs, then return the .where relation.

**Comment by drewda** [comment]
@irees :+1:, looks good.

If/when we're able to implement #278, then we can actually try `find([])`.

**Comment by irees** [comment]
Agreed; I'll keep it in mind.

**Pull request merged**
